add astsbins
the-fast-tracked-programmer/first-contributions pull request #65
Opened 2021-09-04 09:02 UTC by astsbins

completes first-contribution tutorial

2021-09-04 11:14 UTC, Subskii commented on bharat-patodi.md
> -Thanks Adam and Adarsh.
hey @astsbins wondering if you intended to change this file?

2021-09-04 11:17 UTC, Subskii requested changes
Can re-request a review once you've addressed those 2 issues :smiley:

2021-09-04 11:17 UTC, Subskii commented on astbins.md
> +## Hello, I'm Jack
just need to move this one into the `first-contributions` folder within the repo e.g. `first-contributions/astbins.md`

2021-09-04 11:17 UTC, Subskii commented on bharat-patodi.md
> -Thanks Adam and Adarsh.
wondering if you intended to change this file?

2021-09-04 13:26 UTC, astsbins commented on bharat-patodi.md
> -Thanks Adam and Adarsh.
Yeah, it was intentional, but now I realise that its a mistake. There is supposed to be one file per member.

2021-09-05 02:31 UTC, astsbins commented
Is it okay now?

2021-09-05 06:27 UTC, Subskii commented on astbins.md
> +## Hello, I'm Jack
```
first-contributions$ git mv astbins.md first-contributions/astbins.md
first-contributions$ git commit -m "move astbins.md to first-contributions/astbins.md"
```

2021-09-05 06:29 UTC, Subskii commented
Just need to move your file into the `first-contributions/` folder.

Instructions could be clearer we'll get this updated soon.

2021-09-05 06:30 UTC, Subskii commented
Once you've done that and pushed up your changes, re-request a review and we'll get this thing merged for you!

2021-09-05 06:31 UTC, Subskii commented
Oh and finally make sure you update the pull request description with `closes #65` so the issue is properly linked

2021-09-05 08:27 UTC, astsbins commented
closes #65

2021-09-05 08:35 UTC, astsbins commented
is the pull request description just the comments here?

2021-09-06 05:15 UTC, Subskii commented
> is the pull request description just the comments here?

Doesn't seem to link the pull request to the issue if you reference it in the comments :(

Check out [this comment](https://github.com/the-fast-tracked-programmer/first-contributions/pull/73#issuecomment-913349659) for more details

2021-09-06 07:58 UTC, astsbins commented
closes #23

2021-09-06 08:01 UTC, astsbins commented
Hopefully i got it right this time XD

2021-09-06 09:18 UTC, Subskii approved these changes
BINGO!

Great work @astsbins :rocket:!

2021-09-06 09:18 UTC, merged